swagger: "2.0"
info:
  title: ToDo API
  version: 1.0.0
  description: API for managing ToDo items
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

definitions:
  Todo:
    type: object
    required:
      - title
      - completed
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      completed:
        type: boolean
        example: false
      created_at:
        type: string
        format: date-time
        example: "2023-10-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        example: "2023-10-01T12:00:00Z"

paths:
  /todos:
    get:
      summary: Get all ToDo items
      operationId: getTodos
      responses:
        200:
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Todo'
    post:
      summary: Create a new ToDo item
      operationId: createTodo
      parameters:
        - in: body
          name: todo
          required: true
          schema:
            $ref: '#/definitions/Todo'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Todo'
  /todos/{id}:
    parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
    get:
      summary: Get a ToDo item by ID
      operationId: getTodo
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: Not Found
    put:
      summary: Update a ToDo item by ID
      operationId: updateTodo
      parameters:
        - in: body
          name: todo
          required: true
          schema:
            $ref: '#/definitions/Todo'
      responses:
        200:
          description: Updated successfully
          schema:
            $ref: '#/definitions/Todo'
        404:
          description: Not Found
    delete:
      summary: Delete a ToDo item by ID
      operationId: deleteTodo
      responses:
        204:
          description: No Content, deleted successfully
        404:
          description: Not Found