// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTodoNoContentCode is the HTTP code returned for type DeleteTodoNoContent
const DeleteTodoNoContentCode int = 204

/*
DeleteTodoNoContent No Content, deleted successfully

swagger:response deleteTodoNoContent
*/
type DeleteTodoNoContent struct {
}

// NewDeleteTodoNoContent creates DeleteTodoNoContent with default headers values
func NewDeleteTodoNoContent() *DeleteTodoNoContent {

	return &DeleteTodoNoContent{}
}

// WriteResponse to the client
func (o *DeleteTodoNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteTodoNotFoundCode is the HTTP code returned for type DeleteTodoNotFound
const DeleteTodoNotFoundCode int = 404

/*
DeleteTodoNotFound Not Found

swagger:response deleteTodoNotFound
*/
type DeleteTodoNotFound struct {
}

// NewDeleteTodoNotFound creates DeleteTodoNotFound with default headers values
func NewDeleteTodoNotFound() *DeleteTodoNotFound {

	return &DeleteTodoNotFound{}
}

// WriteResponse to the client
func (o *DeleteTodoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
