// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/d-ishizuka/get_it_done/models"
)

// UpdateTodoOKCode is the HTTP code returned for type UpdateTodoOK
const UpdateTodoOKCode int = 200

/*
UpdateTodoOK Updated successfully

swagger:response updateTodoOK
*/
type UpdateTodoOK struct {

	/*
	  In: Body
	*/
	Payload *models.Todo `json:"body,omitempty"`
}

// NewUpdateTodoOK creates UpdateTodoOK with default headers values
func NewUpdateTodoOK() *UpdateTodoOK {

	return &UpdateTodoOK{}
}

// WithPayload adds the payload to the update todo o k response
func (o *UpdateTodoOK) WithPayload(payload *models.Todo) *UpdateTodoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update todo o k response
func (o *UpdateTodoOK) SetPayload(payload *models.Todo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateTodoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateTodoNotFoundCode is the HTTP code returned for type UpdateTodoNotFound
const UpdateTodoNotFoundCode int = 404

/*
UpdateTodoNotFound Not Found

swagger:response updateTodoNotFound
*/
type UpdateTodoNotFound struct {
}

// NewUpdateTodoNotFound creates UpdateTodoNotFound with default headers values
func NewUpdateTodoNotFound() *UpdateTodoNotFound {

	return &UpdateTodoNotFound{}
}

// WriteResponse to the client
func (o *UpdateTodoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
